FROM node:12 AS server
WORKDIR /app
RUN apt install python build-essentials jq
COPY packages/server/package.json packages/server/yarn.lock ./
RUN echo $(cat package.json | jq 'del(.devDependencies)') > package.json
RUN yarn --frozen-lockfile

FROM astefanutti/scratch-node:12
WORKDIR /app
COPY --from=server /app/node_modules node_modules
COPY packages/server .
COPY packages/nuxt/dist public
EXPOSE 8080
ENTRYPOINT [ "node", "dist/index.js" ]
