FROM node:12-alpine AS server
WORKDIR /app
RUN apk add python alpine-sdk
COPY packages/server/package.json packages/server/yarn.lock ./
RUN LDFLAGS='-static-libgcc -static-libstdc++' yarn --production --frozen-lockfile --build-from-source=better-sqlite3,nodejieba

FROM astefanutti/scratch-node:12
WORKDIR /app
COPY --from=server /app .
COPY packages/server .
COPY packages/nuxt/dist public
EXPOSE 8080
ENTRYPOINT [ "node", "dist/index.js" ]
