package server

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/gin-contrib/sessions"
	"github.com/gin-gonic/gin"
	"github.com/patarapolw/zhquiz/server/db"
	"github.com/patarapolw/zhquiz/shared"
	"gorm.io/gorm"

	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	// docs is generated by Swag CLI, you have to import it.
	_ "github.com/patarapolw/zhquiz/docs"
)

/*
@title ZhQuiz API
@version 0.1
@description Chinese quizzing app's API
@termsOfService http://swagger.io/terms/

@contact.name Pacharapol Withayasakpunt
@contact.url https://www.polv.cc
@contact.email polv@polv.cc

@license.name MIT
@license.url https://mit-license.org/
*/
func (res *Resource) registerAPI(r *gin.Engine) {
	r.Use(sessions.Sessions("session", res.Store))

	r.Use(func(c *gin.Context) {
		session := sessions.Default(c)

		if strings.HasPrefix(c.Request.URL.Path, "/api/") {
			authorization := c.GetHeader("Authorization")
			if res.FireAuth != nil && strings.HasPrefix(authorization, "Bearer ") {
				ctx, cancel := context.WithDeadline(context.Background(), time.Now().Add(30*time.Second))
				defer cancel()

				idToken := strings.Split(authorization, " ")[1]
				if token, err := res.FireAuth.VerifyIDToken(ctx, idToken); err == nil {
					if u, err := res.FireAuth.GetUser(ctx, token.UID); err == nil {
						var dbUser db.User

						if r := res.DB.Current.Where("email = ?", u.Email).First(&dbUser); errors.Is(r.Error, gorm.ErrRecordNotFound) {
							dbUser.New(u.Email, u.DisplayName, u.PhotoURL)
							if dbUser.Image == "" {
								dbUser.Image = "https://www.gravatar.com/avatar/0?d=mp"
							}

							if r := res.DB.Current.Create(&dbUser); r.Error != nil {
								panic(r.Error)
							}
						}

						session.Set("userId", dbUser.ID)
					}
				}
			}
		}
	})

	r.GET("/swagger/*any", ginSwagger.WrapHandler(
		swaggerFiles.Handler,
		ginSwagger.URL(fmt.Sprintf("http://localhost:%s/swagger/doc.json", shared.Port())),
	))
}
