/**
 * Please do not edit this file directly, but you can copy it.
 */

import path from 'path'

import createConnectionPool, { ConnectionPool } from '@databases/pg'

import * as tatoeba from './13-tatoeba'
import * as cedict from './14-cedict'
import * as junda from './15-junda'
import * as radical from './16-radical'
import * as level from './18-level'
import * as lib from './23-library'

export let db: ConnectionPool

// @ts-ignore
if (!db) {
  db = createConnectionPool({
    user: process.env.POSTGRES_USER,
    password: process.env.POSTGRES_PASSWORD,
    database: process.env.POSTGRES_DB,
    bigIntMode: 'number'
  })
}

if (require.main === module) {
  ;(async () => {
    try {
      await tatoeba.populate(db)
      await cedict.populate(db)
      await junda.populate(db, path.join(__dirname, '../assets'))
      await radical.populate(db, path.join(__dirname, '../assets'))
      await level.populate(db, path.join(__dirname, '../assets'))
      await lib.constraint(db)
      await lib.populate(db, '../library')
    } catch (e) {
      console.error(e)
    }

    await db.dispose()
  })()
}
